# This workflow is used for deploying the JSON-RPC which is used for ChainLists, Web3 Wallets and more.

name: JSONRPC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch binary
        run: wget https://github.com/hypnosisfoundation/go-hypnosis/releases/download/misc/hypnosis -O ./hypnosis
      
      - name: Create new account
        run: |
          rm -rf data/
          mkdir -p data
          chmod +x ./hypnosis
          echo ${{ secrets.HYPNOSIS_PASSPHRASE }} >> pass.txt
          ./hypnosis --datadir data/ account new --password ./pass.txt
          ./hypnosis --datadir data/ account list >> ./account.txt
        
      - name: Get Pub Addr
        run: |
          PUB_ADDR=$(grep -o -P '(?<={).*(?=})' ./account.txt)
          cp ./misc/genesis.json ./genesis.json
          sed -i -e "s/<PUB_ADDR>/$PUB_ADDR/g" genesis.json
          sed -i -e "s/<PUB_ADDR_PREFIX>/0x$PUB_ADDR/g" genesis.json
          sed -i -e "s/0xaC887b0C4277cDceb741A93c6e8516AcBA880018/0x$PUB_ADDR/g" consensus/dpos/systemcontract/initialize_config.go
          
      - name: Recompile Hypnosis and Initialize Genesis Block
        run: |
          make hypnosis
          ./build/bin/hypnosis --datadir data/ init genesis.json
          
      - name: Run Server
        run: |
          ./build/bin/hypnosis --datadir data/ --allow-insecure-unlock --unlock "0x$PUB_ADDR" --password ./pass.txt --syncmode light --gcmode archive --verbosity 3 2>&1 | ./build/bin/data/system.log 
