# This workflow is used for deploying the JSON-RPC which is used for ChainLists, Web3 Wallets and more.

name: JSONRPC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  
jobs:
  setup:
    env:
      PUB_ADDR: grep -o -P '(?<={).*(?=})' ./account.txt
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch binary
        run: wget https://github.com/hypnosisfoundation/go-hypnosis/releases/download/misc/hypnosis -O ./hypnosis
      
      - name: Create new account
        run: |
          mkdir -p data
          chmod +x ./hypnosis
          echo ${{ secrets.HYPNOSIS_PASSPHRASE }} >> pass.txt
          ./hypnosis --datadir data/ account new --password ./pass.txt
          ./hypnosis --datadir data/ account list >> ./account.txt
        
      - name: Get Pub Addr
        run: echo "$PUB_ADDR"

